---
language: node_js
node_js:
  - "6"

dist: trusty
sudo: false

addons:
  firefox: latest-esr
  chrome: stable

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-beta

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install -g bower phantomjs-prebuilt
  - phantomjs --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait for xfvb to start up

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
